name: Keep Streamlit App Alive

on:
  schedule:
    # Her gün saat 09:00 ve 21:00'de çalışır
    - cron: '0 9,21 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s https://raporlama-meric.streamlit.app > /dev/null
